# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c90bb01f76bda69033e96ba4338ee6bd163b98b6ae910456da7d171d23f15bbc8faf26c5c6b8ecf36b589f95e52b54861eceea362ee7d5e5083d863e3a774a5

test:
  secret_key_base: 5985d879775c096137d9cdf837902b6a0efeb29694a422eacbbaac10a6bfd0b87fd7e90f183ff25e2a01f57ccf1af05ceab963ff05d750eea776a544d552d7c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
